### ISSUE TITLE
[feature request] pass list of ontology acronyms to prefilter the possible search results

### ISSUE THREAD

**Issue by StroemPhi** [NFDI4Chem/ontology-elements#37]
As a user I want to be able to pass a list of ontologies in which OE should look up my term. This list should at best use the official acronmy of an ontology to id it (e.g. `ro` for Relation Ontology).

**Comment by CS76** [comment]
https://nfdi4chem.github.io/ontology-elements/o-autocomplete.html#props

You can provide ontologies acronyms as comma separated values.

**Comment by StroemPhi** [comment]
I guess my feature request was not well enough described. 
Use case:
I don't know/remember in which ontology my term exists, but I only want to search for it in a prespecified set of ontologies (e.g. OBI, CHMO, IAO). So I'd like to pass as parameters the term to search for and a list of ontologies in which to search for it. Maybe like this: `ph value: obi, chmo, iao` or `obi, chmo, iao: ph value`.

**Comment by CS76** [comment]
Yes, you could do this already. The syntax is as follows

nmrcv,chmo,efo: nmr
obi,chmo,iao: ph value

**Comment by StroemPhi** [comment]
Great! Thanks for pointing out. Then I guess this should only be made a bit clearer in the examples of the docs. But otherwise the issue could be closed then, I guess.

**Comment by CS76** [comment]
Closing this in favour of #42
